sudo: required

language: go
go:
- '1.9.2'

services:
  - docker

script:
  - make docker

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker-push-latest;
    else
      make docker-push;
    fi
