---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-0.5.1
spec:
  selector:
    matchLabels:
      app: visit
  replicas: 3
  template:
    metadata:
      labels:
        app: visit
    spec:
      containers:
      - name: visit
        image: partkyle/go-visit:0.5.1
        envFrom:
        - configMapRef:
            name: visit
        ports:
        - containerPort: 80
